export const routes = {
    dashboard: '/',
    clients: '/clients',
    clientsCreate: '/clients/create',
    clientsUpdate: '/clients/:id',
    warehouses: '/warehouses',
    warehousesCreate: '/warehouses/create',
    warehousesUpdate: '/warehouses/:id',
    products: '/products',
    productsCreate: '/products/create',
    productsUpdate: '/products/:id',
    operations: '/operations',
    operationsCreate: '/operations/create',
    operationsDetails: '/operations/details/:id',
    operationsUpdate: '/operations/:id',
    invoices: '/invoices',
    invoiceDetails: '/invoices/details/:id',
    login: '/login',
    register: '/register',
    logout: '/logout',
    notFound: '/*',
};
